### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by xiasnocap** [ItsChasa/Sapphire#2]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 327, in on_ready
    await bot.change_presence(activity=discord.Game(name=config["nuker-user-status"]))
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 1059, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
  File "/usr/local/lib/python3.7/site-packages/discord/gateway.py", line 630, in change_presence
    await self.send(sent)
  File "/usr/local/lib/python3.7/site-packages/discord/gateway.py", line 592, in send
    await self.socket.send_str(data)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

This is my server, I am the owner and still doesnt work.

**Comment by ItsChasa** [comment]
Have you got enough RAM available? I think it is related to this: https://github.com/Rapptz/discord.py/issues/6033

**Comment by ItsChasa** [comment]
Closed, lack of reply.
